### ISSUE TITLE
Cannot install with laravel cashier

### ISSUE THREAD

**Issue by DanielSteadfast** [tightenco/nova-stripe#2]
Hi,

I cant install the package as it requires stripe/stripe-php ^6.12 while laravel cashier only supports ^5.0.

Is there a specific reason for needing the newer stripe version?

Thanks
Daniel

**Comment by samanthamichele7** [comment]
Hey, Daniel! Thanks for checking this package out - I definitely want to make sure that it's compatible with Cashier (as the app I've been testing this on is just straight e-commerce without subscriptions.) I did a bit of research and I don't *think* I'm doing anything currently that requires stripe-php ^6.0 - that said, I also don't want to knock down the dependency version and then lock out anyone who is using the newest version of that package. Let me do a bit of research and figure out the best way to handle, and I'll get back to you a little later today :)

**Comment by DanielSteadfast** [comment]
Awesome thanks!

It looks great btw, really exciting to start using this on projects! :)

**Comment by samanthamichele7** [comment]
Thank you! I'm pumped to be working on it - when I get it Cashier-compatible, please let me know what you think and/or if there are any features we can build to make it more useful for you!

**Comment by samanthamichele7** [comment]
Okay, this should be fixed in [v0.2.1](https://github.com/tightenco/nova-stripe/releases/tag/v0.2.1). I just installed on a Cashier project, and it appears to be working just fine. Thanks for bringing it to my attention, and please let me know if you have any further problems!
